# 使用版本 1 格式，兼容最老的 Docker Compose
nextjs-app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: airbnb_nextjs_app
  restart: unless-stopped
  ports:
    - "8080:8080"
  environment:
    NODE_ENV: production
    PORT: 8080
    NEXT_PUBLIC_API_URL: http://223.4.248.176:3001
    NEXT_PUBLIC_LOCAL_HOST: http://223.4.248.176:3001
    NEXT_PUBLIC_APP_ID: 9527
  volumes:
    - nextjs_logs:/app/logs
  networks:
    - app-network

volumes:
  nextjs_logs:
    driver: local

networks:
  app-network:
    driver: bridge 