version: '3.8'

services:
  # Next.js 前端应用
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airbnb_nextjs_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - nextjs_logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nextjs_logs:
    driver: local

networks:
  app-network:
    driver: bridge 