version: '3.8'

services:
  airbnb-video:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://223.4.248.176:3001
        - NEXT_PUBLIC_LOCAL_HOST=http://223.4.248.176:3001
        - NEXT_PUBLIC_APP_ID=9527
        - NODE_ENV=production
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://223.4.248.176:3001
      - NEXT_PUBLIC_LOCAL_HOST=http://223.4.248.176:3001
      - NEXT_PUBLIC_APP_ID=9527
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: airbnb-video-app